language: ruby

install:
  # Install binary pandoc from Rstudio
  # To use Pandoc, uncomment the following
  # - export PATH="$HOME/pandoc:$PATH"
  # - mkdir $HOME/pandoc
  # - curl -O https://s3.amazonaws.com/rstudio-buildtools/pandoc-1.12.3.zip
  # - unzip -j pandoc-1.12.3.zip pandoc-1.12.3/linux/debian/x86_64/pandoc
  #     -d $HOME/pandoc
  # - chmod +x $HOME/pandoc/pandoc
  # - pandoc --version

  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --quiet

env:
  global:
    secure: "ABqqzmHlGItbbUGDGCRXw8kbNikwOW2vz8CtLb/mIvVdBN/sv/YIM9qbO92sZAOt44lj/cp1uz66N6Jvz0XV3HralPaxKwMUh0OOsm98UN/+LtZejElfvhuPd9GbJr/8R0VxpRVAqw2as2Zw0krABzdr8KkM1v5fS3AqQz9LEqrmWr/O2wa5jXrLTg1Qxa9GcFJeLyACqXL2pMI7J09x1uWJtlcVOSqAI7ZK+PridwbojvgXN58w7ACLwQUyKErysAsgoRSh/A4nK6+Ab1ZVl9y71sXYucDCwmU6nxuNQTYCpDX8aSGO0jWRGvO6DWbcE+uumLevALih0eCNVP5fv1KnWzElzR1NbhSW28j6jbUBbi3vC+zfdGIbu48J2ZFjzUKUrzsN70dwQyw8E4O7TN1qCg/lrvNzMuP8/p38/cnIDAqRuT2sY7sV/R+/usAHAxQpW3KTxAzW7aElpdgiWST2AxSRB3KJt/C87nI5H7Rjntbu4T+GcRtZTwgi+1g0RhUM75ZBJoSPgJBvC7MlsAURRufD4ZvS/mu7e8qypqdzoTjaYqPt73937YQphsGvBUsWhQf9o8/IQCVsKOLqtqKNfvRIqsqLeKryqeQcqWoU5ZtYzjvITlppJOAfkrl95YKDcoydRSTJ1VwL733nUgF+FV4DSHByFyWLxfrYPKY="

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
